##################################################################################
# Cloudify ARIA built in types and plugins definitions.
##################################################################################

plugins:
  aria:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-aria-plugin/archive/master.zip
    package_name: cloudify-aria-plugin
    package_version: '0.1.0'


node_types:

  cloudify.aria.nodes.Service:
    derived_from: cloudify.nodes.Root
    properties:
      csar_path:
        description: >
          Indicates the path to the CSAR file.
        type: string
        required: true
      inputs:
        description: >
          Inputs to the ARIA service template.
        default: {}
      plugins:
        description: >
          A list of plugin names to be installed. These plugins should be located in
          the CSAR plugins dir.
        default: []
    interfaces:
      cloudify.interfaces.lifecycle:
        create: aria.aria_plugin.operations.create
        start: aria.aria_plugin.operations.start
        stop: aria.aria_plugin.operations.stop
        delete: aria.aria_plugin.operations.delete

